// dummyData.js
window.initialEmployees = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@moderntech.com",
    phone: "082-555-0123",
    department: "Software Development",
    position: "Senior Engineer",
    joinDate: "2020-03-15",
    status: "Active",
    salary: { base: 45000, hourlyRate: 260, hoursWorked: 160, allowance: 1500 },
    attendance: { present: 20, absent: 1, leaveBalance: 15 },
    timeOffRequests: [
      {
        id: 101,
        type: "Annual",
        startDate: "2026-07-01",
        endDate: "2026-07-05",
        status: "Pending",
        days: 5,
      },
    ],
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@moderntech.com",
    phone: "071-555-0456",
    department: "Quality Assurance",
    position: "QA Analyst",
    joinDate: "2021-06-10",
    status: "Active",
    salary: { base: 32000, hourlyRate: 185, hoursWorked: 160, allowance: 1000 },
    attendance: { present: 21, absent: 0, leaveBalance: 18 },
    timeOffRequests: [],
  },
  {
    id: 3,
    firstName: "Sipho",
    lastName: "Mokoena",
    email: "s.mokoena@moderntech.com",
    phone: "063-555-0789",
    department: "Software Development",
    position: "Frontend Developer",
    joinDate: "2023-01-15",
    status: "Active",
    salary: { base: 38000, hourlyRate: 220, hoursWorked: 155, allowance: 1200 },
    attendance: { present: 19, absent: 2, leaveBalance: 12 },
    timeOffRequests: [
      {
        id: 102,
        type: "Sick",
        startDate: "2026-06-10",
        endDate: "2026-06-11",
        status: "Approved",
        days: 2,
      },
    ],
  },
  {
    id: 4,
    firstName: "Elena",
    lastName: "Rostova",
    email: "e.rostova@moderntech.com",
    phone: "084-555-1122",
    department: "Customer Support",
    position: "Support Lead",
    joinDate: "2019-11-01",
    status: "Active",
    salary: { base: 28000, hourlyRate: 160, hoursWorked: 168, allowance: 800 },
    attendance: { present: 21, absent: 0, leaveBalance: 22 },
    timeOffRequests: [],
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Kim",
    email: "d.kim@moderntech.com",
    phone: "072-555-3344",
    department: "Sales",
    position: "Account Executive",
    joinDate: "2022-05-20",
    status: "Active",
    salary: { base: 30000, hourlyRate: 173, hoursWorked: 160, allowance: 5000 },
    attendance: { present: 20, absent: 1, leaveBalance: 14 },
    timeOffRequests: [],
  },
  {
    id: 6,
    firstName: "Fatima",
    lastName: "Patel",
    email: "f.patel@moderntech.com",
    phone: "061-555-5566",
    department: "Human Resources",
    position: "HR Manager",
    joinDate: "2018-04-01",
    status: "Active",
    salary: { base: 42000, hourlyRate: 242, hoursWorked: 160, allowance: 1500 },
    attendance: { present: 21, absent: 0, leaveBalance: 25 },
    timeOffRequests: [],
  },
  {
    id: 7,
    firstName: "Michael",
    lastName: "Brown",
    email: "m.brown@moderntech.com",
    phone: "083-555-7788",
    department: "Marketing",
    position: "Media Specialist",
    joinDate: "2024-02-10",
    status: "Active",
    salary: { base: 29000, hourlyRate: 167, hoursWorked: 160, allowance: 1000 },
    attendance: { present: 18, absent: 3, leaveBalance: 15 },
    timeOffRequests: [],
  },
  {
    id: 8,
    firstName: "Charné",
    lastName: "Viljoen",
    email: "c.viljoen@moderntech.com",
    phone: "079-555-9900",
    department: "Software Development",
    position: "UI/UX Designer",
    joinDate: "2022-09-01",
    status: "Active",
    salary: { base: 36000, hourlyRate: 207, hoursWorked: 160, allowance: 1100 },
    attendance: { present: 21, absent: 0, leaveBalance: 17 },
    timeOffRequests: [],
  },
  {
    id: 9,
    firstName: "Amina",
    lastName: "Diallo",
    email: "a.diallo@moderntech.com",
    phone: "062-555-1234",
    department: "Quality Assurance",
    position: "Junior QA Tester",
    joinDate: "2024-06-01",
    status: "Active",
    salary: { base: 22000, hourlyRate: 127, hoursWorked: 160, allowance: 500 },
    attendance: { present: 20, absent: 1, leaveBalance: 15 },
    timeOffRequests: [],
  },
  {
    id: 10,
    firstName: "Thabo",
    lastName: "Ndlovu",
    email: "t.ndlovu@moderntech.com",
    phone: "082-555-5678",
    department: "Sales",
    position: "Sales Director",
    joinDate: "2015-08-24",
    status: "Active",
    salary: { base: 65000, hourlyRate: 375, hoursWorked: 160, allowance: 8500 },
    attendance: { present: 21, absent: 0, leaveBalance: 30 },
    timeOffRequests: [],
  },
  {
    id: 11,
    firstName: "Lisa",
    lastName: "Wong",
    email: "l.wong@moderntech.com",
    phone: "074-555-8910",
    department: "Customer Support",
    position: "Support Agent",
    joinDate: "2023-11-15",
    status: "Active",
    salary: { base: 20000, hourlyRate: 115, hoursWorked: 150, allowance: 400 },
    attendance: { present: 17, absent: 4, leaveBalance: 14 },
    timeOffRequests: [],
  },
  {
    id: 12,
    firstName: "Marcus",
    lastName: "Du Preez",
    email: "m.dupreez@moderntech.com",
    phone: "081-555-2468",
    department: "Software Development",
    position: "DevOps Engineer",
    joinDate: "2021-02-28",
    status: "Active",
    salary: { base: 48000, hourlyRate: 276, hoursWorked: 160, allowance: 2000 },
    attendance: { present: 20, absent: 1, leaveBalance: 16 },
    timeOffRequests: [],
  },
  {
    id: 13,
    firstName: "Sarah",
    lastName: "Jenkins",
    email: "s.jenkins@moderntech.com",
    phone: "065-555-1357",
    department: "Marketing",
    position: "Content Writer",
    joinDate: "2023-05-05",
    status: "On Leave",
    salary: { base: 25000, hourlyRate: 144, hoursWorked: 80, allowance: 600 },
    attendance: { present: 10, absent: 0, leaveBalance: 5 },
    timeOffRequests: [
      {
        id: 103,
        type: "Maternity",
        startDate: "2026-06-01",
        endDate: "2026-08-31",
        status: "Approved",
        days: 65,
      },
    ],
  },
  {
    id: 14,
    firstName: "Owen",
    lastName: "Daniels",
    email: "o.daniels@moderntech.com",
    phone: "073-555-9753",
    department: "Human Resources",
    position: "HR Administrator",
    joinDate: "2024-01-10",
    status: "Active",
    salary: { base: 24000, hourlyRate: 138, hoursWorked: 160, allowance: 700 },
    attendance: { present: 21, absent: 0, leaveBalance: 15 },
    timeOffRequests: [],
  },
  {
    id: 15,
    firstName: "Zanele",
    lastName: "Sithole",
    email: "z.sithole@moderntech.com",
    phone: "084-555-8642",
    department: "Software Development",
    position: "Technical Lead",
    joinDate: "2017-03-01",
    status: "Active",
    salary: { base: 58000, hourlyRate: 334, hoursWorked: 160, allowance: 2500 },
    attendance: { present: 21, absent: 0, leaveBalance: 24 },
    timeOffRequests: [],
  },
];
