const initialEmployees = [
  {
    id: 1,
    firstName: "Sipho",
    lastName: "Nkosi",
    email: "s.nkosi@moderntech.co.za",
    department: "Software Development",
    position: "Senior Engineer",
    status: "Active",
    salary: { base: 65000, hoursWorked: 160, allowance: 4500 },
    attendance: { present: 20, leaveBalance: 15 },
    timeOffRequests: [{ id: 101, type: "Annual", days: 5, status: "Approved" }],
  },
  {
    id: 2,
    firstName: "Amara",
    lastName: "Okocha",
    email: "a.okocha@moderntech.co.za",
    department: "Software Development",
    position: "Full Stack Developer",
    status: "Active",
    salary: { base: 48000, hoursWorked: 160, allowance: 3000 },
    attendance: { present: 21, leaveBalance: 18 },
    timeOffRequests: [],
  },
  {
    id: 3,
    firstName: "Liam",
    lastName: "Naidoo",
    email: "l.naidoo@moderntech.co.za",
    department: "Quality Assurance",
    position: "QA Automation Lead",
    status: "Active",
    salary: { base: 42000, hoursWorked: 155, allowance: 2500 },
    attendance: { present: 19, leaveBalance: 12 },
    timeOffRequests: [{ id: 102, type: "Sick", days: 2, status: "Pending" }],
  },
  {
    id: 4,
    firstName: "Chantel",
    lastName: "De Beer",
    email: "c.debeer@moderntech.co.za",
    department: "Human Resources",
    position: "HR Manager",
    status: "Active",
    salary: { base: 55000, hoursWorked: 160, allowance: 4000 },
    attendance: { present: 22, leaveBalance: 24 },
    timeOffRequests: [],
  },
  {
    id: 5,
    firstName: "Thabo",
    lastName: "Mokoena",
    email: "t.mokoena@moderntech.co.za",
    department: "Customer Support",
    position: "Support Specialist",
    status: "Active",
    salary: { base: 28000, hoursWorked: 160, allowance: 1500 },
    attendance: { present: 20, leaveBalance: 14 },
    timeOffRequests: [],
  },
  {
    id: 6,
    firstName: "Elena",
    lastName: "Smits",
    email: "e.smits@moderntech.co.za",
    department: "Sales",
    position: "Account Executive",
    status: "Active",
    salary: { base: 35000, hoursWorked: 140, allowance: 8000 },
    attendance: { present: 18, leaveBalance: 11 },
    timeOffRequests: [{ id: 103, type: "Annual", days: 3, status: "Pending" }],
  },
  {
    id: 7,
    firstName: "Zayd",
    lastName: "Patel",
    email: "z.patel@moderntech.co.za",
    department: "Marketing",
    position: "Digital Strategist",
    status: "Active",
    salary: { base: 38000, hoursWorked: 160, allowance: 2000 },
    attendance: { present: 21, leaveBalance: 19 },
    timeOffRequests: [],
  },
  {
    id: 8,
    firstName: "Sarah",
    lastName: "Jenkins",
    email: "s.jenkins@moderntech.co.za",
    department: "Software Development",
    position: "UI/UX Designer",
    status: "On Leave",
    salary: { base: 44000, hoursWorked: 80, allowance: 2000 },
    attendance: { present: 10, leaveBalance: 8 },
    timeOffRequests: [
      { id: 104, type: "Annual", days: 10, status: "Approved" },
    ],
  },
  {
    id: 9,
    firstName: "Naledi",
    lastName: "Zulu",
    email: "n.zulu@moderntech.co.za",
    department: "Quality Assurance",
    position: "Manual Tester",
    status: "Active",
    salary: { base: 26000, hoursWorked: 160, allowance: 1200 },
    attendance: { present: 22, leaveBalance: 16 },
    timeOffRequests: [],
  },
  {
    id: 10,
    firstName: "Michael",
    lastName: "Pretorius",
    email: "m.pretorius@moderntech.co.za",
    department: "Software Development",
    position: "DevOps Engineer",
    status: "Active",
    salary: { base: 58000, hoursWorked: 160, allowance: 3500 },
    attendance: { present: 20, leaveBalance: 21 },
    timeOffRequests: [],
  },
  {
    id: 11,
    firstName: "Fatima",
    lastName: "Allie",
    email: "f.allie@moderntech.co.za",
    department: "Human Resources",
    position: "Recruitment Officer",
    status: "Active",
    salary: { base: 32000, hoursWorked: 160, allowance: 1800 },
    attendance: { present: 21, leaveBalance: 15 },
    timeOffRequests: [],
  },
  {
    id: 12,
    firstName: "Johan",
    lastName: "Botha",
    email: "j.botha@moderntech.co.za",
    department: "Sales",
    position: "Sales Director",
    status: "Active",
    salary: { base: 75000, hoursWorked: 160, allowance: 12000 },
    attendance: { present: 20, leaveBalance: 30 },
    timeOffRequests: [],
  },
  {
    id: 13,
    firstName: "Palesa",
    lastName: "Madiba",
    email: "p.madiba@moderntech.co.za",
    department: "Customer Support",
    position: "Support Lead",
    status: "Active",
    salary: { base: 36000, hoursWorked: 160, allowance: 2200 },
    attendance: { present: 22, leaveBalance: 13 },
    timeOffRequests: [],
  },
  {
    id: 14,
    firstName: "David",
    lastName: "Walker",
    email: "d.walker@moderntech.co.za",
    department: "Marketing",
    position: "Content Creator",
    status: "Active",
    salary: { base: 30000, hoursWorked: 150, allowance: 1500 },
    attendance: { present: 19, leaveBalance: 17 },
    timeOffRequests: [{ id: 105, type: "Sick", days: 3, status: "Denied" }],
  },
  {
    id: 15,
    firstName: "Aisha",
    lastName: "Banda",
    email: "a.banda@moderntech.co.za",
    department: "Software Development",
    position: "Junior Developer",
    status: "Active",
    salary: { base: 29000, hoursWorked: 160, allowance: 1000 },
    attendance: { present: 20, leaveBalance: 14 },
    timeOffRequests: [],
  },
];
